apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: ECR
      prefix: AWSACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com
      api_url: https://AWSACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com
      credentials: ext:/app/config/ecr.sh
      default: true
  ecr.sh: |
    #!/bin/sh
    aws ecr --region ap-northeast-2 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-ssh-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-ssh-config