apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secret-app
  namespace: vault
spec:
  project: devops
  destination:
    name: cluster-staging
    namespace: vault
  source:
    path: iac/vault/secret
    repoURL: git@github.com:ORGANIZATION/argocd.git
    targetRevision: main
    plugin:
      name: argocd-vault-plugin
  syncPolicy:
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
    - Replace=true
    # The retry feature is available since v1.7
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
