apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-secret
    app.kubernetes.io/part-of: argocd-image-updater
  annotations:
    avp.kubernetes.io/path: "devops/data/aws-ecr-token"
  name: aws-ecr-secret
data:
  .dockerconfigjson: <.dockerconfigjson | base64encode>