apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-secret
    app.kubernetes.io/part-of: argocd-image-updater
  annotations:
    avp.kubernetes.io/path: "devops/data/aws-ecr-token"
  name: aws-ecr-key-secret
data:
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID | base64encode>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY | base64encode>