kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  annotations:
    avp.kubernetes.io/path: "devops/data/argocd-vault-plugin"
type: Opaque
data:
  AVP_AUTH_TYPE: <AVP_AUTH_TYPE | base64encode>
  AVP_ROLE_ID: <AVP_ROLE_ID | base64encode>
  AVP_SECRET_ID: <AVP_SECRET_ID | base64encode>
  AVP_TYPE: <AVP_TYPE | base64encode>
  VAULT_ADDR: <VAULT_ADDR | base64encode>